fixtures:
  repositories:
    "apt":
      "repo": "git://github.com/puppetlabs/puppetlabs-apt.git"
      "ref": "1.3.0"
    "stdlib":
      "repo": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      "ref": "4.4.0"
  symlinks:
    "rightscale": "#{source_dir}"
