fixtures:
  repositories:
    "apt":
      "repo": "git://github.com/puppetlabs/puppetlabs-apt.git"
      "ref": "2.2.1"
    "sudo":
      "repo": "https://github.com/saz/puppet-sudo.git"
      "ref": "v3.0.1"
    "stdlib":
      "repo": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      "ref": "4.4.0"
  symlinks:
    "rightscale": "#{source_dir}"
