language: ruby

matrix:
  fast_finish: true
  include:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION=3.7.0
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=3.7.0
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=3.8.0
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=3.8.0
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION=4.0.0

sudo: false
bundler_args: --without development
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec SPEC_OPTS='--format documentation --color'"

