language: ruby
bundler_args: --without development
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec SPEC_OPTS='--format documentation --color'"
rvm:
  - 1.9.3
  - 2.0.0
env:
 - PUPPET_GEM_VERSION="~> 3.6.0"
 - PUPPET_GEM_VERSION="~> 3.7.0"
sudo: false